name: 'CI-changelog-builder'
on:
#   push:
#     branches:
#     - main
#     - release
#     - develop
#     tags:
#       - '*'
  workflow_dispatch:
    inputs:
      fromTag:
        description: 'Set fromtag Version'
        required: true
      toTag:
        description: 'Set totag Version'
        required: true
  
jobs:
  release:
#     if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        with:
          owner: "mikepenz"
          repo: "hello-world-ssl"
          ignorePreReleases: "false"
          fromTag: ${{ github.event.inputs.fromTag }}
          toTag: ${{ github.event.inputs.toTag }}
          token: ${{ secrets.PAT }}
