name: 'CI-changelog-builder'
on:
  push:
    branches:
    - main
    - release
    - develop
#     tags:
#       - '*'
  workflow_dispatch:
  
jobs:
  release:
#     if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        with:
          configuration: "configuration.json"
          token: ${{ secrets.PAT }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
