name: 'CI-changelog-builder'
on:
  push:
    branches:
    - main
    - release
    - develop
#     tags:
#       - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@2.9.0
        with:
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
