name: 'CI-changelog-builder'
on:
  push:
    branches:
#     - main
#     - release
    - develop
    tags:
      - '*'
  workflow_dispatch:
#     inputs:
#       fromTag:
#         description: 'Set fromtag Version'
#         required: true
#       toTag:
#         description: 'Set totag Version'
#         required: true
  
jobs:
  release:
#     if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
        
      - name: "Build Changelog"
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        with:
          owner: "mikepenz"
          configuration: "configuration.json"
          repo: "hello-world-ssl"
          ignorePreReleases: "false"
#           fromTag: ${{ github.event.inputs.fromTag }}
#           toTag: ${{ github.event.inputs.toTag }}
          token: ${{ secrets.PAT }

# name: 'CI-changelog-builder'
# on:
#   push:
#     tags:
#       - 'RL*'

# jobs:
#   release:
#     if: startsWith(github.ref, 'refs/tags/')
#     runs-on: ubuntu-latest
#     steps:
#       - name: Build Changelog
#         id: github_release
#         uses: mikepenz/release-changelog-builder-action@v2.9.0
#         with:
#           configuration: "configuration.json"
#           ignorePreReleases: "true"
#           token: ${{ secrets.PAT }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT }}

