name: Review Assign

on:
  pull_request:
    branches:
    - 'develop'

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - if: github.base_ref == 'master' # base branch name is 'master'
        run: echo REVIEWERS=prabhneetgit >> $GITHUB_ENV
      - if: startsWith(github.base_ref, 'develop') # base branch name starts with 'develop_'
        run: echo REVIEWERS=prabhneetgit >> $GITHUB_ENV
      - if: startsWith(github.event.pull_request.title, 'bug') # title starts with 'bug'
        run: echo REVIEWERS=prabhneetgit >> $GITHUB_ENV
      - if: contains(github.event.pull_request.body, 'enhancement') # body contains 'enhancement'
        run: echo REVIEWERS=prabhneetgit >> $GITHUB_ENV
      - uses: hkusu/review-assign-action@v1
        with:
#          assignees: ${{ github.actor }}
          reviewers: ${{ env.REVIEWERS }}